const templates = {
   mercedes: {
      lease:
         "Lease Disclaimer: {YEAR} Mercedes-Benz {MODEL} Available only to qualified customers through Mercedes-Benz Financial Services (where applicable to advertised lease) at participating authorized Mercedes-Benz dealers through {EXPIRATION_DATE}. Not everyone will qualify. Advertised {MONTHLY_PAYMENT} per month for {LEASE_TERM} months lease rate based on MSRP of {MSRP} less the suggested dealer contribution resulting in a total gross capitalized cost of {GROSS_CAP_COST}. DEALER SETS FINAL PRICE. Dealer contribution may vary and could affect your actual lease payment. Includes Destination Charge and optional ({OPTIONAL_PACKAGE}). Excludes title, taxes, registration, license fees, insurance, dealer prep, and additional options. Total monthly payments equal {TOTAL_MONTHLY_PAYMENTS}. Cash due at signing includes {CASH_DUE_AT_SIGNING} capitalized cost reduction, {ACQUISITION_FEE} acquisition fee, and first month's lease payment of {FIRST_MONTH_PAYMENT}. No security deposit required. Total payments equal {TOTAL_PAYMENTS}. At lease end, lessee pays for any amounts due under the lease, any official fees and taxes related to the scheduled termination, excess wear and use plus {OVERAGE_COST_PER_MILE}/mile over {MILEAGE_ALLOWANCE} miles and a {TURN_IN_FEE} vehicle turn-in fee. Purchase option at lease end for {PURCHASE_OPTION} plus taxes (and any other fees and charges due under the applicable lease agreement). Subject to credit approval. Specific vehicles are subject to availability and may need to be ordered. See participating dealer for details. Offers not valid in Puerto Rico. Offer expires {EXPIRATION_DATE}.",
      buy:
         "{YEAR} {MODEL}. Qualified customers only. {APR_RATE}% APR financing for {APR_TERM} months at {MONTHLY_COST_PER_1000_FINANCED} per month, per $1,000 financed. Excludes leases and balloon contracts. Available only at participating authorized Mercedes-Benz dealers through Mercedes-Benz Financial Services. Must take delivery of vehicle by {EXPIRATION_DATE}. Specific vehicles are subject to availability and may have to be ordered. Subject to credit approval by lender. Rate applies only to Mercedes-Benz model vehicle listed. Not everyone will qualify. Offer excludes certain optional equipment shown or described. See your authorized Mercedes-Benz dealer for complete details on this and other finance offers. Offer not valid in Puerto Rico."
   },
   kia: {
      lease:
         "{YEAR} Kia {MODEL}. Lease for {MONTHLY_PAYMENT}/mo for {LEASE_TERM} mos. {CASH_DUE_AT_SIGNING} due at signing. Stock: {STOCK_NUMBER}. VIN: {VIN}. MSRP: {MSRP}. {LEASE_TERM} Months incentives include: {LEASE_CASH} LEASE CASH, {MILITARY_INCENTIVE} MILITARY, {LOYALTY_INCENTIVE} LOYALTY. Residual value {RESIDUAL_VALUE}. Includes TT&L and doc fee. {MILEAGE_ALLOWANCE} miles/yr. On approved credit. No security deposit. Subject to credit approval by Kia Finance America (KFA). Lessee is responsible for insurance, maintenance, repairs, {OVERAGE_COST_PER_MILE} per mile over {MILEAGE_ALLOWANCE} miles/year, excess wear, and a termination fee of up to {TURN_IN_FEE}. Offer expires {EXPIRATION_DATE}.",
      buy:
         "{YEAR} Kia {MODEL}. Finance for {APR_RATE} APR for {APR_TERM} months. For qualified customers. {APR_RATE} APR available on new {YEAR} {BRAND} {MODEL} vehicles for up to {APR_TERM} months. {MONTHLY_COST_PER_1000_FINANCED} per month per $1,000 financed at {APR_TERM} months. APR financing available, subject to credit approval by Kia Finance America (KFA), through (KFA), to very well-qualified buyers and not available on balloon financing. Only a limited number of customers will qualify for advertised APR. No down payment required. Must take delivery from a participating dealer and from retail stock by {EXPIRATION_DATE}. New vehicles only. Finance contract must be signed and dated no later than {EXPIRATION_DATE}."
   }
};

export { templates }; 
